aayu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #A
    path('greened/', include('greened.urls')),
    path('', include('greened.urls')),
    #A
]

greened/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from greened.views import *

urlpatterns = [
        #path('',
            #TemplateView.as_view(template_name="city.html")
            #CitiesView.as_view()
            #CityListView.as_view()
        #),
        path('greened/city/<int:city_id>/branch/<int:branch_id>/', branch_people, name="branch_people"),
        path('greened/city/<int:city_id>/', details, name="details"),
        path('greened/', index, name='index'),
        path('', index, name='index'),
]

algo/models.py
from django.db import models

# Create your models here.

base/models.py
from django.db import models


class Base(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.SmallIntegerField(default=True) # status: values 0-Deactivated, 1-Active, 2-Pending, null-probably untouched yet
    class Meta:
        abstract = True

cities/models.py
from django.db import models

# Create your models here.
from base.models import Base

class State(Base):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name.capitalize()


class City(Base):
    name = models.CharField(max_length=256)
    latitude = models.DecimalField(decimal_places=7, max_digits=10)
    longitude = models.DecimalField(decimal_places=7, max_digits=10)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    #area_square_meters = models.PositiveIntegerField() # Area in Square-KiloMeters, Mumbai=603.4 SqKilo
    area = models.DecimalField(decimal_places=5, max_digits=15, default=None) # Area in Square-KiloMeters, Mumbai=603.4 SqKilo

    def __str__(self):
        return self.name.capitalize()


#class CityBranch(BaseModel):
    #pass

companies/models.py
from django.db import models

# Create your models here.

from base.models import Base
#from base.includes import *
from cities.models import City

class Company(Base):
    """
    """
    name = models.CharField(max_length=256)
    #address = models.CharField()
    #pincode = models.PositiveIntegerField()
    #area_square_meters = models.PositiveIntegerField() # Area of company in Square-Meters

    def __str__(self):
        return self.name


class Branch(Base):
    """
    """
    name = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    pincode = models.PositiveIntegerField()
    area = models.DecimalField(decimal_places=5, max_digits=15, default=None) # Area of company in Square-Meters
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    #contact_number
    #contact_email
    def __str__(self):
        return self.name + " , in city: " + self.city.name.capitalize()

identification/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Mobile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    number = models.IntegerField()
    imei = models.IntegerField()

userprofile/models.py
from django.db import models
from django.db.models import signals 
# Create your models here.
from django.contrib.auth.models import User
from base.models import Base
from cities.models import City
from companies.models import Branch

from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(Base):

    class WorkType(models.TextChoices):
        LA = ('LA', 'LABOUR'),
        IT = ('IT', 'INFO TECH')

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.PositiveIntegerField(10, default=None, null=True)
    work_type = models.CharField(max_length=16,choices=WorkType.choices, default=WorkType.LA)
    branch = models.ForeignKey(Branch, default=1, on_delete=models.CASCADE)
    city = models.ForeignKey(City, default=1, on_delete=models.CASCADE)
    
    #location = models.CharField(max_length=30, blank=True)
    #birthdate = models.DateField(null=True, blank=True)
    #role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)

    def __str__(self):  # __unicode__ for Python 2
        return self.user.username + " " + self.work_type


# SAVE SIGNAL
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

greened/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView

# Create your views here.
from cities.models import City
from companies.models import Branch
from algo import algo

class CitiesView(TemplateView):
    template_name = "city.html"

class CityListView(TemplateView):
    model = City

def index(request):
    cities = City.objects.all()

    context = {'cities': cities}

    return render(request, 'index.html', context)


def details(request, city_id):
    city = City.objects.get(id=city_id)
    branches = city.branch_set.all()

    context = {'city': city, 'branches': branches}

    return render(request, 'details.html', context)

def branch_people(request, city_id, branch_id):
    city = City.objects.get(id=city_id)
    branch = Branch.objects.get(id=branch_id)

    min_dist = algo.minimum_distance_to_be_maintained()
    handle = round( algo.how_many_can_be_handled(branch.area) )

    allowed_handle = round( handle - (handle * 20/100) )

    context = {
        'city': city,
        'branch': branch,
        'min_dist': min_dist,
        'handle': handle,
        'allowed_handle': allowed_handle,
        'not_allowed_handle': round( handle - allowed_handle ),
    }

    return render(request, 'branch_people.html', context)

userprofile/views.py
from django.shortcuts import render

# Create your views here.

greened/templates/branch_people.html
<div 
	style="background-color: lightgreen"
>
	<h2>
		Go To <a href="/">Home</a>
	</h2>
</div>

<div
	style="background-color: lightgreen"
>

<!--
The branch of Company {{branch.company}}
at {{branch.address}}
has {{branch.userprofile_set.count}} number of people working
with and Area of {{branch.area}} Square Meters.
With the minimum distance to be maintained at {{min_dist}},
The Max Number of People this Company Branch can handle is {{handle}}
-->

	<div>
		<b>
			Area of the place {{branch.company.name}} at {{branch.address}} in Square-Meters? 
			<i 
				style="background-color: yellow"
			>
				{{branch.area}} 
			</i>
			Square-Meters
		</b>
		<br />
		<br />
		<b>
		Number of People currently working?
			<i 
				style="background-color: yellow"
			>
		{{branch.userprofile_set.count}}
			</i>
		</b>
		<br />
		<br />
		<b>
			Minimum Distance to be Maintained from Each Other?
			<i 
				style="background-color: yellow"
			>
			{{min_dist}} 
			Meters
			</i>
		</b>
		<br />
		<br />
		<b>
			According to the algorithm in an Area of 
			<i 
				style="background-color: yellow"
			>
			{{branch.area}} 
			</i>
			SqMeters, 
			<br />
			<br />
			The Max number of people working at this place simultaneously can be: At Max 
			<i 
				style="background-color: yellow"
			>
				{{handle}}
			</i> 
			People.
			<br />
			Who have the best probablity, to always be 
			<i 
				style="background-color: yellow"
			>
			{{min_dist}} 
			</i>
			Meters apart from Each Other.
			<br />
			But out of these only 
			<i 
				style="background-color: yellow"
			>
			{{allowed_handle}} 
			</i>
			are in need, for reasons, like, type of work like they maybe Labour class, 
			Urgency of work, Importance of work/position, Need etc.
			<br />
			So they can be given higher priority for a Pass/QR Code to come out of their homes.
			<br />
			The rest of 
			<i 
				style="background-color: yellow"
			>
			{{not_allowed_handle}}
			</i>
			are at a lower priority to have a need to come out of their homes, 
			for the same reasons, like Type of work, Urgency of work, Importance, Need.
		<br />
		</b>
		<h3>
			Conclusion: 
		</h3>
		<b>

			So only 
			<i 
				style="background-color: yellow"
			>
				{{allowed_handle}}
			</i> 
			can be selected At Max to come out of their homes to work at this place, 
			<br />
			whether they are Labour worker at this place, IT, Management or any other.
		</b>
	</div>
	<br />
	<h4>
		This is a demonstration of areas at modest levels.
		<br />
		In this same manner, these Algorithms can scale and be applied to any Place/Space/Area/Locality/Street/City at larger levels.
		<br />
		For eg. If there is a DMart store in Borivali, which has "x" SqMeter area, we can figure out, 
		<br />
		What should be the max Number of People who can be inside the Store simutaneously at the same time.
		<br />
		Same goes for larger places like Street/Locality/City etc. 
		<br />
		<h1>
			Features:
		</h1>
				More feature that can be added: 
				There can be a lot more things that can be done with this software that we can explain to you
		<ul>
			<li>
				Instead of Random selection of people, rather Select only those people to come out, who are really In Need.
			</li>
			<li>
				People who have IT or ITES or other such Company/JobType, can be given lower priority than People who work in 
				a company dealing with Manual Labour
			</li>
			<li>
				There can be a request/emergency form, where people can place a request that they really need 
				to come out of house for some important work, and the system can consider those people.
			</li>
		</ul>


</div>

greened/templates/city.html
<div>
	CITY
</div>
<div>
	{% for i in cities %}
	<div>
		<a href="{{i.name}}"></a>
	</div>
	{% endfor %}
</div>

greened/templates/city_list.html
<div>
	CityLIST
</div>

greened/templates/details.html
<div 
	style="background-color: lightgreen"
>
	<h2>
		Go To <a href="/">Home</a>
	</h2>
</div>

<div
	style="background-color: lightgreen"
>
	<h3>
		The City of {{city.name}} has these Places ( viz. Offices, Companies, Road, Street )
		<br />
		Please select a place to see:
			<ol>
				<li>
					How much is the Area of that particular place in Square Meters
				</li>
				<li>
					And How many people at the Max can be allowed to work in that Square Meter of Area, at the same time
				</li>
			</ol>

	</h3>
	{% for v in branches %}

	<div>
		<a href="/greened/city/{{city.id}}/branch/{{v.id}}">
			{{v.company.name}} at {{v.address.capitalize}}
		</a>
			with an Area of {{v.area}} Square Meters 
	</div>

	{% endfor %}
</div>

greened/templates/index.html
<div 
	style="background-color: lightgreen"
>
	<h2>
		Go To <a href="/">Home</a>
	</h2>
	<h2>
		Please read all the simple text to understand the software clearly. 
		You may risk not understanding the software, if you miss reading the explanation text of each page.
	</h2>
	<h2>
		Solution:
	</h2>
	<b> 
		<p>
		Some number of people will be algorithmically selected based on importance, urgency, need, priority etc. 
		</p>
		and only those people will be allowed to come out of their houses to work or carry out external tasks.
		These people will be given a QR code on their mobile, and they have to show that QR code at train station to get a ticket, 
		in the ricksha to get a ride, show at the builiding entrance to enter etc.

		How these people will be selected, please follow instructions below.
	</b>

</div>

<div
	style="background-color: lightgreen"
>
	<h3>Data available for the following cities, please click on a city and see the companies inside that city and the company details</h3>
	{% for v in cities %}

	<div>
		<a href="/greened/city/{{v.id}}/">{{v.name}}</a>
	</div>

	{% endfor %}
</div>